name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y golang git build-essential

    - name: Build the project
      run: |
        cd $GITHUB_WORKSPACE
        go build -o ai-commit
        # makepkg -si --noconfirm

    - name: Verify the build
      run: |
        ./ai-commit --version

    # - name: Upload package
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ai-commit
    #     path: "*.pkg.tar.zst"
